#--cpus 4 --mem 10g --disk 100g
load "../Vagrantfile"
Vagrant.configure("2") do |config|
  config.vm.hostname = "gitlab"
  config.vm.network "private_network", ip: "192.168.56.103"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "10240"
    vb.cpus = "4"
  end
end
