load "../Vagrantfile"
Vagrant.configure("2") do |config|
  config.vm.hostname = "bash"
  config.vm.network "private_network", ip: "192.168.56.100"
  config.vm.provision "bootstrap", type: "shell", path: "provision.sh", reboot: true
  config.vm.provision :reload
end
