#--cpus 4 --mem 6g --disk 100g
load "../Vagrantfile"
Vagrant.configure("2") do |config|
  config.vm.hostname = "kafka"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
    vb.cpus = "4"
  end
end
