load "../Vagrantfile"
Vagrant.configure("2") do |config|
  config.vm.hostname = "bash"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end
end
