apiVersion: v1
kind: Namespace
metadata:
  name: theia
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: theia
  namespace: theia
spec:
  rules:
  - host: theia.info
    http:
      paths:
      - backend:
          serviceName: theia
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: theia
 namespace: theia
spec:
 ports:
 - port: 80
   targetPort: 3000
 selector:
   app: theia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia
  name: theia
  namespace: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - image: theiaide/theia-full:latest
        imagePullPolicy: Always
        name: theia
        ports:
        - containerPort: 3000
